name: "Build Android app"

on:
  workflow_dispatch:
    branches: [dev]
    # can add push and pull_request here 
    
env:
  APP_CENTER_TOKEN: ${{ secrets.APP_CENTER_TOKEN_MYAPP_ANDROID_TEST  }}  
  APP_NAME: ${{ 'G1-TableTime/TableTime'  }}  
  UPLOAD_FILE: ${{ './android/app/build/outputs/bundle/release/app-release.aab'  }}  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          java-version: "12"
          distribution: "adopt"
          cache: "gradle"

      - name: Setup Node  
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Run Yarn Install
        run: |
             cd ./packages/app-mobile/
             npm i -g corepack
             yarn install      
             
      - name: Build application
        run: |
             cd ./android
             chmod +x gradlew
             ./gradlew assembleDebug
             
      - name: Decode Keystore
        env:
           ENCODED_STRING: ${{ secrets.SIGNING_KEY_STORE_BASE64 }}
           SIGNING_KEY_STORE_PATH: ${{ secrets.SIGNING_KEY_STORE_PATH }}
 
        run: |
           echo $ENCODED_STRING > keystore-b64.txt
           base64 -d keystore-b64.txt > $SIGNING_KEY_STORE_PATH

      - name: Build Build Release apk
        env:
           SIGNING_KEY_STORE_PATH: ${{ secrets.SIGNING_KEY_STORE_PATH }}
           SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
           SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
           SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
        run: |
             cd ./android
             chmod +x gradlew
             ./gradlew assembleRelease

      - name: Build Build Release Bundle
        env:
           SIGNING_KEY_STORE_PATH: ${{ secrets.SIGNING_KEY_STORE_PATH }}
           SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
           SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
           SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
        run: |
             cd ./android
             chmod +x gradlew
             ./gradlew bundleRelease

      - name: Upload application Debug Apk
        uses: actions/upload-artifact@v2
        with:
          name: debug-apk
          path: ./android/app/build/outputs/apk/debug
          retention-days: 3
             
      - name: Upload application Release Apk
        uses: actions/upload-artifact@v2
        with:
          name: realease-apk
          path: ./android/app/build/outputs/apk/release
          retention-days: 3

      - name: Upload application Release Bundle
        uses: actions/upload-artifact@v2
        with:
          name: realease-aab
          path: ./android/app/build/outputs/bundle/release/
          retention-days: 3
                
          
      - name: Upload to App Center
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: ${{ env.APP_NAME }}
          token: ${{ env.APP_CENTER_TOKEN }}
          group: Developer
          file: ${{ env.UPLOAD_FILE }}
